name: Justfile Stuff

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1
      - name: Test
        run: just test
