name: Test & Lint

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Install JQ
        run: just install-jq
      - name: Install GCloud
        run: just install-gcloud
